import Foundation

/// How to draw a document's stored icon. Cookie-Web stores either an emoji or
/// `ms:<icon_name>`, a Material Symbols glyph (src/lib/documentIcons.js).
/// iOS has no Material Symbols font, so a symbol icon maps to the closest SF
/// Symbol, and anything unmapped, empty, or malformed falls back to a generic
/// document symbol. The raw `ms:` text is never shown.
enum DocumentIcon: Equatable {
    case emoji(String)
    case systemImage(String)

    static let fallbackSystemImage = "doc.text"
    private static let symbolPrefix = "ms:"

    init(_ value: String?) {
        let trimmed = value?.trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        if trimmed.isEmpty {
            self = .systemImage(Self.fallbackSystemImage)
        } else if trimmed.hasPrefix(Self.symbolPrefix) {
            let name = String(trimmed.dropFirst(Self.symbolPrefix.count))
            self = .systemImage(Self.sfSymbols[name] ?? Self.fallbackSystemImage)
        } else {
            self = .emoji(trimmed)
        }
    }

    /// Material Symbols name → SF Symbol for the common picks in the web
    /// catalogue. Every value must exist on the deployment target
    /// (DocumentIconTests checks each one resolves).
    static let sfSymbols: [String: String] = [
        // General & files
        "description": "doc.text",
        "article": "doc.richtext",
        "draft": "doc",
        "note_alt": "note.text",
        "sticky_note_2": "note.text",
        "edit_note": "square.and.pencil",
        "folder": "folder",
        "folder_open": "folder",
        "topic": "folder",
        "inventory_2": "archivebox",
        "archive": "archivebox",
        "book": "book",
        "menu_book": "book",
        "auto_stories": "book",
        "library_books": "books.vertical",
        "bookmark": "bookmark",
        "bookmarks": "bookmark",
        "collections_bookmark": "bookmark",
        "checklist": "checklist",
        "task_alt": "checkmark.circle",
        "list": "list.bullet",
        "format_list_bulleted": "list.bullet",
        "assignment": "list.clipboard",
        "content_paste": "doc.on.clipboard",
        "label": "tag",
        "sell": "tag",
        "push_pin": "pin",
        "attach_file": "paperclip",
        "link": "link",
        "table_chart": "tablecells",
        "grid_on": "tablecells",
        "dashboard": "square.grid.2x2",
        "lightbulb": "lightbulb",
        "tips_and_updates": "lightbulb",
        "emoji_objects": "lightbulb",
        // Work
        "work": "briefcase",
        "business_center": "briefcase",
        "badge": "person.text.rectangle",
        "groups": "person.3",
        "diversity_3": "person.3",
        "group": "person.2",
        "person": "person",
        "event": "calendar",
        "calendar_month": "calendar",
        "schedule": "clock",
        "alarm": "alarm",
        "timer": "timer",
        "hourglass_empty": "hourglass",
        "flag": "flag",
        "tour": "flag",
        "campaign": "megaphone",
        "trending_up": "chart.line.uptrend.xyaxis",
        "monitoring": "chart.line.uptrend.xyaxis",
        "insights": "chart.xyaxis.line",
        "analytics": "chart.bar",
        "bar_chart": "chart.bar",
        "leaderboard": "chart.bar",
        "query_stats": "chart.bar",
        "pie_chart": "chart.pie",
        "target": "target",
        "gavel": "hammer",
        "balance": "scalemass",
        "apartment": "building.2",
        "domain": "building.2",
        "corporate_fare": "building.2",
        // Home
        "home": "house",
        "house": "house",
        "cottage": "house",
        "bed": "bed.double",
        "hotel": "bed.double",
        "chair": "chair",
        "weekend": "sofa",
        "kitchen": "refrigerator",
        "bathtub": "bathtub",
        "shower": "shower",
        "cleaning_services": "bubbles.and.sparkles",
        "local_laundry_service": "washer",
        "garage": "car",
        "construction": "hammer",
        "handyman": "wrench.and.screwdriver",
        "build": "wrench.and.screwdriver",
        "plumbing": "wrench",
        "electrical_services": "powerplug",
        "light": "lightbulb",
        "pets": "pawprint",
        "family_restroom": "figure.2.and.child.holdinghands",
        // Travel
        "flight": "airplane",
        "flight_takeoff": "airplane.departure",
        "luggage": "suitcase",
        "travel_explore": "globe",
        "public": "globe",
        "language": "globe",
        "map": "map",
        "explore": "safari",
        "place": "mappin",
        "location_on": "mappin.and.ellipse",
        "beach_access": "beach.umbrella",
        "pool": "figure.pool.swim",
        "directions_car": "car",
        "train": "tram",
        "directions_bus": "bus",
        "directions_bike": "bicycle",
        "sailing": "sailboat",
        "hiking": "figure.hiking",
        "landscape": "mountain.2",
        "camping": "tent",
        // Food & drink
        "restaurant": "fork.knife",
        "restaurant_menu": "fork.knife",
        "local_cafe": "cup.and.saucer",
        "coffee": "cup.and.saucer",
        "cake": "birthday.cake",
        "local_bar": "wineglass",
        "wine_bar": "wineglass",
        "liquor": "wineglass",
        "nutrition": "carrot",
        "set_meal": "fish",
        "fastfood": "takeoutbag.and.cup.and.straw",
        "lunch_dining": "takeoutbag.and.cup.and.straw",
        "local_grocery_store": "cart",
        "shopping_cart": "cart",
        "shopping_bag": "bag",
        "shopping_basket": "basket",
        // Nature & weather
        "eco": "leaf",
        "yard": "leaf",
        "grass": "leaf",
        "compost": "leaf",
        "potted_plant": "leaf",
        "park": "tree",
        "forest": "tree",
        "nature": "tree",
        "spa": "camera.macro",
        "local_florist": "camera.macro",
        "recycling": "arrow.3.trianglepath",
        "water_drop": "drop",
        "sunny": "sun.max",
        "wb_sunny": "sun.max",
        "cloud": "cloud",
        "thunderstorm": "cloud.bolt",
        "ac_unit": "snowflake",
        "bolt": "bolt",
        "local_fire_department": "flame",
        "nights_stay": "moon",
        "bedtime": "moon",
        // Tech
        "code": "chevron.left.forwardslash.chevron.right",
        "data_object": "chevron.left.forwardslash.chevron.right",
        "integration_instructions": "chevron.left.forwardslash.chevron.right",
        "terminal": "terminal",
        "computer": "desktopcomputer",
        "laptop": "laptopcomputer",
        "smartphone": "iphone",
        "developer_mode": "iphone",
        "tablet_mac": "ipad",
        "keyboard": "keyboard",
        "mouse": "computermouse",
        "memory": "cpu",
        "dns": "server.rack",
        "storage": "server.rack",
        "database": "server.rack",
        "cloud_upload": "icloud.and.arrow.up",
        "bug_report": "ladybug",
        "wifi": "wifi",
        "router": "wifi",
        "settings": "gearshape",
        "science": "testtube.2",
        "biotech": "testtube.2",
        // Money
        "payments": "banknote",
        "savings": "banknote",
        "attach_money": "dollarsign.circle",
        "account_balance": "building.columns",
        "account_balance_wallet": "wallet.pass",
        "credit_card": "creditcard",
        "receipt_long": "doc.plaintext",
        "request_quote": "doc.plaintext",
        "calculate": "function",
        "functions": "function",
        "price_check": "tag",
        "local_offer": "tag",
        "currency_exchange": "arrow.left.arrow.right",
        // Health
        "favorite": "heart",
        "monitor_heart": "waveform.path.ecg",
        "medical_services": "cross.case",
        "local_hospital": "cross.case",
        "medication": "pills",
        "vaccines": "syringe",
        "fitness_center": "dumbbell",
        "directions_run": "figure.run",
        "self_improvement": "figure.mind.and.body",
        "psychology": "brain.head.profile",
        "psychiatry": "brain.head.profile",
        // Education & hobbies
        "school": "graduationcap",
        "history_edu": "pencil",
        "draw": "pencil.tip",
        "translate": "character.bubble",
        "quiz": "questionmark.circle",
        "help": "questionmark.circle",
        "grade": "star",
        "star": "star",
        "emoji_events": "trophy",
        "workspace_premium": "rosette",
        "architecture": "ruler",
        "palette": "paintpalette",
        "brush": "paintbrush",
        "photo_camera": "camera",
        "music_note": "music.note",
        "piano": "pianokeys",
        "movie": "film",
        "mic": "mic",
        "headphones": "headphones",
        "sports_esports": "gamecontroller",
        "sports_soccer": "soccerball",
        "theater_comedy": "theatermasks",
        // Symbols
        "check_circle": "checkmark.circle",
        "info": "info.circle",
        "warning": "exclamationmark.triangle",
        "error": "exclamationmark.circle",
        "priority_high": "exclamationmark.circle",
        "lock": "lock",
        "key": "key",
        "visibility": "eye",
        "shield": "shield",
        "policy": "shield",
        "health_and_safety": "shield",
        "verified": "checkmark.seal",
        "new_releases": "seal",
        "diamond": "diamond",
        "auto_awesome": "sparkles",
        "celebration": "party.popper",
        "mood": "face.smiling",
        "thumb_up": "hand.thumbsup",
        "all_inclusive": "infinity",
        "extension": "puzzlepiece",
        "category": "square.on.circle",
        "interests": "square.on.circle",
    ]
}
